# Page settings
baseurl = "localhost:1313"
title = "Elate theme"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Rexdale Masjid"
    home = "Home"
    work = "Work"
    testimonials = "News &amp; Updates"
    services = "Services"
    about = "About"
    contact = "Contact"
    prayers='Prayer Times'


    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Time left until..."
    subtitle = 'Another free HTML5 bootstrap template by <a href="http://freehtml5.co/" target="_blank" title="Free HTML5 Bootstrap Templates">FREEHTML5.co</a> released under <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank">Creative Commons 3.0</a><br> ported for Hugo by <a href="http://saey55.gitlab.io/pietercv" target="_blank">Pieter Saey</a>'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "HIFZ SCHOOL PROGRAM"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Hifz"
      subtitle = "Full Time"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Hifz"
      subtitle = "Part Time"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Naazira"
      subtitle = "sd"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Madrassa"
      subtitle = ""

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Summer School"
      subtitle = ""

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "News"
    description = "For latest news and updates, follow us on twitter @RexdaleMasjid!"

  # Services section
  [params.services]
    enable = false
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Hifz Full time &amp; Part time"
      description = "It is the aim of the Hifz Program for students to complete the Hifz-ul Qur’an under the guidance of qualified and experienced Teachers according to the tenets of Tajweed and Tarteel. "
      icon = "icon-anchor"
    [[params.services.item]]
      title = "Summer School"
      description = "Details for our summer school program will be available soon."      
      icon = "icon-monitor"
    [[params.services.item]]
      title = "Naazira"
      description = "Details for our Naazira program will be available soon."
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Madrassa"
      description = "Details for our Madrassa will be available soon."
      icon = "icon-video2"

    

  # About section
  [params.about]
    enable = true
    title = "About"
    description = """Rexdale Jame Masjid was first established in 1987 as a musalla in a small shop on the second floor with praying capacity of 30 - 35. \
          Just after a year this musalla, shifted to a bigger location to accommodate 100-125 worshippers. \
          In 1992 it again relocated to a still bigger unit with praying capacity of 150-200. \
          During the year 2001 the existing unit was extended by adding one more unit, thus maintaining the total praying capacity of 300 - 400.


Alhamdulillah, this musalla being one of the oldest facilities, serving successfully the neighboring Muslim community for over 20 years.
"""
  # Counters section
  [params.prayers]
    enable = true
    title = "Prayer Times"
    background = "full_image_1.jpg"

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = false
    title = "Get in touch"
    description = "Please feel free to contact us or drop by anytime!"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "127 Westmore Dr, Etobicoke, ON M9V 3Y6"],
        ["icon-phone", "(416) 744-3474"],
        ["icon-envelope", "info@rexdaleMasjid.ca"]
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Rexdale Masjid. All Rights Reserved.'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        #["icon-youtube", "#youtube"]
      ]
